[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings
[context.production]
  # Environmental variables for production
  environment = { 
    NODE_VERSION = "18", 
    NPM_FLAGS = "--no-optional", 
    ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", 
    ROLLUP_NATIVE_PLUGIN = "none"
  }

# Branch deploy context: all deploys that are not from the Production branch
# will inherit these settings
[context.branch-deploy]
  # Different settings for branch deploys
  command = "npm run build"
  environment = { 
    ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", 
    ROLLUP_NATIVE_PLUGIN = "none"
  }

# Development context: deploys from branches that are not Production
# and not branch deploys, like Pull Requests
[context.dev]
  command = "npm run build"
  environment = { 
    ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", 
    ROLLUP_NATIVE_PLUGIN = "none"
  }

# Specific branch deployment
[context.staging]
  command = "npm run build"
  environment = { 
    NODE_ENV = "staging", 
    ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", 
    ROLLUP_NATIVE_PLUGIN = "none"
  }

# Redirects and rewrite rules
[[redirects]]
  # Single-page app (SPA) redirect
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set on different URL patterns
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://res.cloudinary.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://res.cloudinary.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.cloudinary.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Add more specific cache settings for asset types
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configure Netlify build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # Lighthouse plugin configuration
  [plugins.inputs]
    output_path = "lighthouse-results"

# Performance optimization settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true