[build]
command = "npm run build"
publish = "dist"
base ="/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Disable Cloudinary plugin
[[plugins]]
package = "netlify-plugin-cloudinary"
[plugins.inputs]
enabled = false

[build.environment]
  NODE_VERSION = "18"