# Voltant Energy Netlify Configuration
# Based on project structure with proper routing for different pages

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Environment variables for various deployment contexts
[context.production]
  # Environmental variables for production
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--no-optional", ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", ROLLUP_NATIVE_PLUGIN = "none" }

[context.branch-deploy]
  command = "npm run build"
  environment = { ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", ROLLUP_NATIVE_PLUGIN = "none" }

[context.dev]
  command = "npm run build"
  environment = { ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", ROLLUP_NATIVE_PLUGIN = "none" }

[context.staging]
  command = "npm run build"
  environment = { NODE_ENV = "staging", ROLLUP_SKIP_LOAD_NATIVE_PLUGIN = "true", ROLLUP_NATIVE_PLUGIN = "none" }

# Primary SPA redirect - must be the last rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset-specific cache control for performance optimization

# JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SVG files
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Image files
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Font files
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Audio/Video files
[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Assets folder
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Global headers for security and best practices
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://res.cloudinary.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://res.cloudinary.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.cloudinary.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Configure Netlify build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "lighthouse-results"

# Cloudinary plugin configuration
[[plugins]]
  package = "netlify-plugin-cloudinary"

# Performance optimization settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true